import { RegisterUserForm } from "@/components/RegisterUserForm";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cadastro",
  description: "Generated by create next app",
  icons: "/vaccine.svg",
};

export default function RegisterUser() {
  return <RegisterUserForm />;
}
