import "date-fns/locale/pt-BR";
import { LoginForm } from "@/components/LoginForm";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
  icons: "/vaccine.svg",
};

const Login = () => {
  return <LoginForm />;
};

export default Login;
