import { UpdatePasswordForm } from "@/components/PasswordForm";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Atualizar Senha",
  description: "Generated by create next app",
  icons: "/vaccine.svg",
};

export default function UpdatePassword() {
  return <UpdatePasswordForm />;
}
