import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Providers from "@/providers/query-client-provider";
import { UserContextProvider } from "@/contexts/userContext";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vacina Certa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <link rel="icon" href="/vacina.png" sizes="any" />;
      <body className={poppins.className}>
        <Providers>
          <UserContextProvider>{children}</UserContextProvider>
        </Providers>
      </body>
    </html>
  );
}
